project_id = "xfnbyqqejpnfupbkspck"
[functions.submit-quote]
enabled = true
verify_jwt = true
import_map = "./functions/submit-quote/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/submit-quote/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/submit-quote/*.html" ]

[functions.quotient-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/quotient-webhook/deno.json"
entrypoint = "./functions/quotient-webhook/index.ts"
