// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfnbyqqejpnfupbkspck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmbmJ5cXFlanBuZnVwYmtzcGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTU3MTUsImV4cCI6MjA2NTczMTcxNX0.Ah0PgjAOSKgvneqGsdduB63GVUfHNE_8oGEMvjUshoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);